### ISSUE TITLE
OUI-offline sqlite

### ISSUE THREAD

**Issue by coolacid** [logstash-plugins/logstash-filter-oui#1]
oui-offline (best available) has a requirement for sqlite database - this requires a native extension. This is going to cause some problems with this logstash filter.

**Comment by purbon** [comment]
There is an input that uses sqlite (https://github.com/logstash-plugins/logstash-input-sqlite), you might take some ideas on how to run it from there.

**Comment by coolacid** [comment]
Pushed fix to upstream, closing this.
